Add main.py, and templates
AlekseyStakhov/common pull request #8
Opened 2019-11-02 01:17 UTC by AlekseyStakhov

2019-11-05 06:13 UTC, ekut2104 requested changes

2019-11-05 06:13 UTC, ekut2104 commented on Flask_1/templates/base.html
> +<nav class="navbar navbar-expand-lg navbar-dark primary-color">
![Screenshot from 2019-11-05 08-04-04](https://user-images.githubusercontent.com/24397874/68182737-f0b9bd00-ffa2-11e9-8d3b-fb966bd6fe9d.png)
Глянь будь-ласка колір бекграунду...бо не видно навбар

2019-11-05 06:13 UTC, ekut2104 commented on Flask_1/templates/base.html
> +</div>
Посилання на домашню сторінку відображається і на домашній сторінці) - не впевнений що це доцільно ;)

2019-11-06 15:03 UTC, AlekseyStakhov commented on Flask_1/templates/base.html
> +<nav class="navbar navbar-expand-lg navbar-dark primary-color">
Дім, з цим навбаром мені допоміг Саша Клімач. Він скачав з https://mdbootstrap.com/docs/jquery/getting-started/download/ бібліотеку і помістив її в файл "Static". В мене відображається корректно.
![Снимок экрана от 2019-11-06 16-44-42](https://user-images.githubusercontent.com/55539586/68309571-4d0e0100-00b7-11ea-83cc-8fb975c62db0.png)

2019-11-06 15:04 UTC, AlekseyStakhov commented on Flask_1/templates/base.html
> +</div>
Добре :). Пофіксав!

2019-11-06 15:07 UTC, AlekseyStakhov commented on Flask_1/templates/base.html
> +<nav class="navbar navbar-expand-lg navbar-dark primary-color">
Він просто сказав не коммітить цей "static" 
![Снимок экрана от 2019-11-06 17-06-06](https://user-images.githubusercontent.com/55539586/68309965-f05f1600-00b7-11ea-8b63-bfd1248a0edb.png)

2019-11-07 12:45 UTC, ekut2104 approved these changes

2019-11-07 12:45 UTC, ekut2104 commented on Flask_1/templates/base.html
> +<nav class="navbar navbar-expand-lg navbar-dark primary-color">
ну тому коректно в тебе і відображається)) бо є цей файл)
`<nav class="navbar navbar-expand-lg navbar-dark primary-color">`
заміни приміром на 
`<nav class="navbar navbar-expand-lg navbar-dark bg-dark">`

2019-11-11 22:10 UTC, merged